//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.App", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt.
        /// </summary>
        internal static string CaiDat {
            get {
                return ResourceManager.GetString("CaiDat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Căn hộ.
        /// </summary>
        internal static string CanHo {
            get {
                return ResourceManager.GetString("CanHo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinh sửa căn hộ.
        /// </summary>
        internal static string CanHo_ChinhSua {
            get {
                return ResourceManager.GetString("CanHo_ChinhSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết căn hộ.
        /// </summary>
        internal static string CanHo_ChiTiet {
            get {
                return ResourceManager.GetString("CanHo_ChiTiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách căn hộ.
        /// </summary>
        internal static string CanHo_DanhSach {
            get {
                return ResourceManager.GetString("CanHo_DanhSach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập căn hộ từ tập tin excel.
        /// </summary>
        internal static string CanHo_ImportExcel {
            get {
                return ResourceManager.GetString("CanHo_ImportExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập dữ liệu từ Excel.
        /// </summary>
        internal static string CanHo_NhapLieuExcel {
            get {
                return ResourceManager.GetString("CanHo_NhapLieuExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân giỏ hàng cho sales.
        /// </summary>
        internal static string CanHo_PhanChoSale {
            get {
                return ResourceManager.GetString("CanHo_PhanChoSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý căn hộ.
        /// </summary>
        internal static string CanHo_QuanLy {
            get {
                return ResourceManager.GetString("CanHo_QuanLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm căn hộ.
        /// </summary>
        internal static string CanHo_ThemMoi {
            get {
                return ResourceManager.GetString("CanHo_ThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm căn hộ mới.
        /// </summary>
        internal static string CanHo_TinMoi {
            get {
                return ResourceManager.GetString("CanHo_TinMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa căn hộ.
        /// </summary>
        internal static string CanHo_Xoa {
            get {
                return ResourceManager.GetString("CanHo_Xoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string CapNhat {
            get {
                return ResourceManager.GetString("CapNhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấu Hình.
        /// </summary>
        internal static string CauHinh {
            get {
                return ResourceManager.GetString("CauHinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string ChinhSua {
            get {
                return ResourceManager.GetString("ChinhSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        internal static string ChinhSuaTinDang {
            get {
                return ResourceManager.GetString("ChinhSuaTinDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết tin rao.
        /// </summary>
        internal static string ChiTietTinRao {
            get {
                return ResourceManager.GetString("ChiTietTinRao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ đầu tư.
        /// </summary>
        internal static string ChuDauTu {
            get {
                return ResourceManager.GetString("ChuDauTu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chủ nhà.
        /// </summary>
        internal static string ChuNha {
            get {
                return ResourceManager.GetString("ChuNha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tin.
        /// </summary>
        internal static string DangTin {
            get {
                return ResourceManager.GetString("DangTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tin đăng.
        /// </summary>
        internal static string DangTin_DanhSach {
            get {
                return ResourceManager.GetString("DangTin_DanhSach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý tin đăng.
        /// </summary>
        internal static string DangTin_QuanLy {
            get {
                return ResourceManager.GetString("DangTin_QuanLy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng tin mới.
        /// </summary>
        internal static string DangTin_TinMoi {
            get {
                return ResourceManager.GetString("DangTin_TinMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục đăng tin.
        /// </summary>
        internal static string DanhMucDangTin {
            get {
                return ResourceManager.GetString("DanhMucDangTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dự án.
        /// </summary>
        internal static string DuAn {
            get {
                return ResourceManager.GetString("DuAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        internal static string KhachHang {
            get {
                return ResourceManager.GetString("KhachHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch sử thao tác.
        /// </summary>
        internal static string LichSuLog {
            get {
                return ResourceManager.GetString("LichSuLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại Dự Án.
        /// </summary>
        internal static string LoaiDuAn {
            get {
                return ResourceManager.GetString("LoaiDuAn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu Cầu của khách hàng.
        /// </summary>
        internal static string Menu_GuiYeuCau {
            get {
                return ResourceManager.GetString("Menu_GuiYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        internal static string NhanVien {
            get {
                return ResourceManager.GetString("NhanVien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm người dùng.
        /// </summary>
        internal static string NhomNguoiDung {
            get {
                return ResourceManager.GetString("NhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa nhóm người dùng.
        /// </summary>
        internal static string NhomNguoiDungSua {
            get {
                return ResourceManager.GetString("NhomNguoiDungSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phân giỏ hàng cho Salesman.
        /// </summary>
        internal static string PhanGioHangChoSale {
            get {
                return ResourceManager.GetString("PhanGioHangChoSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quay lại.
        /// </summary>
        internal static string QuayLai {
            get {
                return ResourceManager.GetString("QuayLai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài Khoản.
        /// </summary>
        internal static string TaiKhoan {
            get {
                return ResourceManager.GetString("TaiKhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa Tài khoản.
        /// </summary>
        internal static string TaiKhoanSua {
            get {
                return ResourceManager.GetString("TaiKhoanSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Tài khoản.
        /// </summary>
        internal static string TaiKhoanThem {
            get {
                return ResourceManager.GetString("TaiKhoanThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo dự án mới.
        /// </summary>
        internal static string TaoDuAnMoi {
            get {
                return ResourceManager.GetString("TaoDuAnMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SÀN GIAO DỊCH BẤT ĐỘNG SẢN DANH LAND.
        /// </summary>
        internal static string TenDonVi {
            get {
                return ResourceManager.GetString("TenDonVi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DanhLand Control.
        /// </summary>
        internal static string TenUngDung {
            get {
                return ResourceManager.GetString("TenUngDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string ThemMoi {
            get {
                return ResourceManager.GetString("ThemMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm nhóm người dùng.
        /// </summary>
        internal static string ThemNhomNguoiDung {
            get {
                return ResourceManager.GetString("ThemNhomNguoiDung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thoát.
        /// </summary>
        internal static string Thoat {
            get {
                return ResourceManager.GetString("Thoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin.
        /// </summary>
        internal static string ThongTin {
            get {
                return ResourceManager.GetString("ThongTin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếp tục.
        /// </summary>
        internal static string TiepTuc {
            get {
                return ResourceManager.GetString("TiepTuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình trạng căn hộ.
        /// </summary>
        internal static string TinhTrangCanHo {
            get {
                return ResourceManager.GetString("TinhTrangCanHo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string XoaTinDang {
            get {
                return ResourceManager.GetString("XoaTinDang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xuất Excel.
        /// </summary>
        internal static string XuatExcel {
            get {
                return ResourceManager.GetString("XuatExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa yêu cầu.
        /// </summary>
        internal static string YeuCau_ChinhSua {
            get {
                return ResourceManager.GetString("YeuCau_ChinhSua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách yêu cầu.
        /// </summary>
        internal static string YeuCau_DanhSachYeuCau {
            get {
                return ResourceManager.GetString("YeuCau_DanhSachYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý yêu cầu của khách hàng.
        /// </summary>
        internal static string YeuCau_QuanLyYeuCau {
            get {
                return ResourceManager.GetString("YeuCau_QuanLyYeuCau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo mới yêu cầu.
        /// </summary>
        internal static string YeuCau_TaoMoi {
            get {
                return ResourceManager.GetString("YeuCau_TaoMoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yêu cầu.
        /// </summary>
        internal static string YeuCau_YeuCau {
            get {
                return ResourceManager.GetString("YeuCau_YeuCau", resourceCulture);
            }
        }
    }
}
