//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_canho_ghichu
    {
        public long id_ghichu { get; set; }
        public Nullable<long> canho { get; set; }
        public string noidung { get; set; }
        public Nullable<int> nguoidung { get; set; }
        public Nullable<int> nhom_nguoidung { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
    }
}
