//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_canho
    {
        public decimal IDCanHo { get; set; }
        public long IDChuNha { get; set; }
        public decimal IDDuAn { get; set; }
        public string Thap { get; set; }
        public string Tang { get; set; }
        public string SoCan { get; set; }
        public Nullable<double> DienTich { get; set; }
        public Nullable<decimal> HuongCua { get; set; }
        public Nullable<decimal> HuongBanCong { get; set; }
        public string PhongNgu { get; set; }
        public string WC { get; set; }
        public string View { get; set; }
        public int IDTinhTrangCH { get; set; }
        public Nullable<long> IDLoaiCanHo { get; set; }
        public Nullable<decimal> IDLoaiBanGiao { get; set; }
        public string VideoLink { get; set; }
        public string MatKhauCua { get; set; }
        public Nullable<double> GiaHopDong { get; set; }
        public string GiaHopDongDVT { get; set; }
        public Nullable<double> GiaChuNhaGui { get; set; }
        public string GiaChuNhaGuiDVT { get; set; }
        public Nullable<double> GiaChotBan { get; set; }
        public string GiaChotBanDVT { get; set; }
        public Nullable<double> GiaChaoBan { get; set; }
        public string GiaChaoBanDVT { get; set; }
        public Nullable<double> GiaThueNet { get; set; }
        public string GiaThueNetDVT { get; set; }
        public Nullable<double> GiaThueBaoPhi { get; set; }
        public string GIaThueBaoPhiDVT { get; set; }
        public Nullable<double> GiaHopDongUSD { get; set; }
        public Nullable<double> GiaChuNhaGuiUSD { get; set; }
        public Nullable<double> GiaChaoBanUSD { get; set; }
        public Nullable<double> GiaChotBanUSD { get; set; }
        public Nullable<double> GiaThueNetUSD { get; set; }
        public Nullable<double> GiaThueBaoPhiUSD { get; set; }
        public string GhiChuAdmin { get; set; }
        public string GhiChuQuanLy { get; set; }
        public string GhiChuSales { get; set; }
        public Nullable<int> NguoiDungTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiDungSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<System.DateTime> NgayDel { get; set; }
        public Nullable<decimal> NguoiDungDel { get; set; }
        public Nullable<double> GiaGoc { get; set; }
        public string GiaGocDVT { get; set; }
        public Nullable<double> GiaGocUSD { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string GIaBanDVT { get; set; }
        public Nullable<double> GiaBanUSD { get; set; }
    }
}
