//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_canho_chunha
    {
        public long Id { get; set; }
        public long IdCanho { get; set; }
        public long IdChuNha { get; set; }
        public Nullable<long> IdNguoiDung { get; set; }
        public System.DateTime Ngay { get; set; }
        public string GhiChu { get; set; }
    }
}
