//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_canho_lichsugia
    {
        public long Id { get; set; }
        public Nullable<long> IDCanHo { get; set; }
        public string GiaHopDong { get; set; }
        public string GiaChuNhaGui { get; set; }
        public string GiaThue { get; set; }
        public string GiaChaoBan { get; set; }
        public string GiaChotBan { get; set; }
        public string GhiChu { get; set; }
        public decimal NguoiDungTao { get; set; }
        public System.DateTime NgayTao { get; set; }
    }
}
