//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_canho_tempitem
    {
        public long ID { get; set; }
        public string TenChuNha { get; set; }
        public string QuocTich { get; set; }
        public string LienHe { get; set; }
        public Nullable<decimal> IDDuAn { get; set; }
        public string Thap { get; set; }
        public string Tang { get; set; }
        public string SoCan { get; set; }
        public Nullable<double> DienTich { get; set; }
        public Nullable<decimal> IDHuongCua { get; set; }
        public Nullable<decimal> IDHuongBanCong { get; set; }
        public string PhongNgu { get; set; }
        public string WC { get; set; }
        public string VIEW { get; set; }
        public Nullable<int> IDTinhTrangCH { get; set; }
        public Nullable<decimal> IDLoaiCanHo { get; set; }
        public Nullable<decimal> IDLoaiBanGiao { get; set; }
        public string MatKhauCua { get; set; }
        public Nullable<double> TienGiaChuNhaGui { get; set; }
        public string GiaChuNhaGuiDVT { get; set; }
        public Nullable<double> GiaChuNhaGuiUSD { get; set; }
        public Nullable<double> TienGiaChotBan { get; set; }
        public string GiaChotBanDVT { get; set; }
        public Nullable<double> GiaChotBanUSD { get; set; }
        public Nullable<double> TienGiaGoc { get; set; }
        public string GiaGocDVT { get; set; }
        public Nullable<double> GiaGocUSD { get; set; }
        public Nullable<double> TienGiaBan { get; set; }
        public string GiaBanDVT { get; set; }
        public Nullable<double> GiaBanUSD { get; set; }
        public Nullable<double> TienGiaThue { get; set; }
        public string GiaThueDVT { get; set; }
        public Nullable<double> GiaThueUSD { get; set; }
        public Nullable<double> TienGiaThueBaoPhi { get; set; }
        public string GiaThueBaoPhiDVT { get; set; }
        public Nullable<double> GiaThueBaoPhiUSD { get; set; }
        public string GhiChuAdmin { get; set; }
        public string GhiChuQuanLy { get; set; }
        public string GhiChuSales { get; set; }
        public Nullable<decimal> NguoiDungTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
