//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_canho_giohangsalesman
    {
        public long ID { get; set; }
        public Nullable<long> IDCanHo { get; set; }
        public decimal NguoiDung { get; set; }
        public decimal NguoiPhan { get; set; }
        public System.DateTime NgayPhan { get; set; }
        public bool Del { get; set; }
    }
}
