//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_configs
    {
        public string con_key { get; set; }
        public string con_value { get; set; }
        public Nullable<bool> mahoa { get; set; }
        public string GhiChu { get; set; }
    }
}
