//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_canho_images
    {
        public long ID { get; set; }
        public long IDCanHo { get; set; }
        public string Url { get; set; }
        public string TenHinh { get; set; }
        public Nullable<bool> HinhDaiDien { get; set; }
        public string Size { get; set; }
    }
}
