//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_dm_quan_huyen
    {
        public string id_quan_huyen { get; set; }
        public string ten_quan_huyen { get; set; }
        public string id_tinh_thanh_pho { get; set; }
    }
}
