//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_dangtin
    {
        public decimal id { get; set; }
        public string hinh_dai_dien { get; set; }
        public string hinh_dai_dien_key { get; set; }
        public Nullable<decimal> du_an { get; set; }
        public string du_an_key { get; set; }
        public Nullable<decimal> chu_dau_tu { get; set; }
        public string chu_dau_tu_key { get; set; }
        public Nullable<decimal> trang_thai { get; set; }
        public string trang_thai_key { get; set; }
        public Nullable<decimal> loai { get; set; }
        public string loai_key { get; set; }
        public string loai_kinh_doanh { get; set; }
        public string loai_kinh_doanh_key { get; set; }
        public Nullable<decimal> huong { get; set; }
        public string huong_key { get; set; }
        public Nullable<decimal> views { get; set; }
        public string views_key { get; set; }
        public string dia_chi { get; set; }
        public string dia_chi_key { get; set; }
        public string dien_tich { get; set; }
        public string dien_tich_key { get; set; }
        public string phong_ngu { get; set; }
        public string phong_ngu_key { get; set; }
        public string wc { get; set; }
        public string wc_key { get; set; }
        public string gia_ban_ty { get; set; }
        public string gia_ban_ty_key { get; set; }
        public string gia_ban_trieu { get; set; }
        public string gia_ban_trieu_key { get; set; }
        public string gia_ban_usd { get; set; }
        public string gia_ban_usd_key { get; set; }
        public string gia_thue_ty { get; set; }
        public string gia_thue_ty_key { get; set; }
        public string gia_thue_trieu { get; set; }
        public string gia_thue_trieu_key { get; set; }
        public string gia_thue_usd { get; set; }
        public string gia_thue_usd_key { get; set; }
        public Nullable<System.DateTime> ngay_khoi_tao { get; set; }
        public Nullable<long> loai_ban_giao { get; set; }
        public string loai_ban_giao_key { get; set; }
        public string vi_tri_key { get; set; }
        public Nullable<long> vi_tri { get; set; }
        public Nullable<decimal> NguoiDung { get; set; }
    }
}
