//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_historys
    {
        public long Id { get; set; }
        public string Key { get; set; }
        public string Content { get; set; }
        public string Type { get; set; }
        public string TableName { get; set; }
        public string LinkView { get; set; }
        public decimal NguoiDung { get; set; }
        public System.DateTime Ngay { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
    }
}
