//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_loaiduan
    {
        public int ID { get; set; }
        public string TenLoaiDuAn { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> NguoiDungTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<decimal> NguoiDungSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
