//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_nhom_nguoi_dung
    {
        public int id_nhom_nguoi_dung { get; set; }
        public int id_level { get; set; }
        public string ten_nhom_nguoi_dung { get; set; }
        public string mo_ta { get; set; }
        public Nullable<decimal> NguoiDungTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<decimal> NguoiDungSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
    }
}
