//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_nguoidung_tinhtrang
    {
        public int id_nguoidung_tinhtrang { get; set; }
        public string ten_nguoidung_tinhtrang { get; set; }
    }
}
