//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_nguoidung_phanquyen_nhomnguoidung
    {
        public int id { get; set; }
        public decimal nguoi_dung { get; set; }
        public decimal id_nhom_nguoi_dung { get; set; }
    }
}
