//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_quyen
    {
        public int id { get; set; }
        public string tenquyen { get; set; }
        public int nhom_quyen { get; set; }
        public int STT { get; set; }
        public bool hienthi { get; set; }
        public string GhiChu { get; set; }
    }
}
