//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_thongbao_phanquyen
    {
        public long thongbaophanquyen { get; set; }
        public int thongbao { get; set; }
        public int loaithongbao { get; set; }
        public decimal nguoitao { get; set; }
        public decimal nguoidung { get; set; }
        public System.DateTime ngay { get; set; }
    }
}
