//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_yeucau_canho
    {
        public int yeu_cau { get; set; }
        public int can_ho { get; set; }
        public Nullable<System.DateTime> ngay_xem_nha { get; set; }
        public Nullable<int> trang_thai_xem { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> nguoi_tao { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<int> nguoi_sua { get; set; }
        public Nullable<System.DateTime> ngay_sua { get; set; }
        public Nullable<bool> da_xoa { get; set; }
        public Nullable<int> nguoi_xoa { get; set; }
        public Nullable<System.DateTime> ngay_xoa { get; set; }
    }
}
