//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_yeucau
    {
        public decimal id { get; set; }
        public string so_dien_thoai { get; set; }
        public string ten_khach_hang { get; set; }
        public string dia_chi { get; set; }
        public string zalo { get; set; }
        public string messenger { get; set; }
        public string nguon_khach { get; set; }
        public Nullable<System.DateTime> ngay_tao { get; set; }
        public Nullable<int> nguoi_tao { get; set; }
        public Nullable<System.DateTime> ngay_sua { get; set; }
        public Nullable<int> nguoi_sua { get; set; }
        public string so_phong_ngu { get; set; }
        public string email_khach_hang { get; set; }
        public string nghe_nghiep { get; set; }
        public string tang_thap_nhat { get; set; }
        public string tang_cao_nhat { get; set; }
        public string gia_tu { get; set; }
        public string gia_den { get; set; }
        public string ghi_chu { get; set; }
        public Nullable<int> nguoi_phu_trach { get; set; }
        public string views { get; set; }
        public string tien_ich_bo_sung { get; set; }
        public Nullable<int> trang_thai { get; set; }
        public Nullable<System.DateTime> du_kien_xem_nha { get; set; }
        public Nullable<double> dt_quan_tam_tu { get; set; }
        public Nullable<double> dt_quan_tam_den { get; set; }
        public Nullable<bool> da_xoa { get; set; }
        public Nullable<int> nguoi_xoa { get; set; }
        public Nullable<System.DateTime> ngay_xoa { get; set; }
    }
}
