//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class dl_yeucau_trangthai
    {
        public long ID { get; set; }
        public long IdYeuCau { get; set; }
        public int Trang_Thai { get; set; }
        public string GhiChu { get; set; }
        public decimal NguoiDungTao { get; set; }
        public System.DateTime NgayTao { get; set; }
        public Nullable<decimal> NguoiDungXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
    }
}
