//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RealEstateEntities : DbContext
    {
        public RealEstateEntities()
            : base("name=RealEstateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dl_canho> dl_canho { get; set; }
        public virtual DbSet<dl_canho_chunha> dl_canho_chunha { get; set; }
        public virtual DbSet<dl_canho_ghichu> dl_canho_ghichu { get; set; }
        public virtual DbSet<dl_canho_images> dl_canho_images { get; set; }
        public virtual DbSet<dl_canho_lichsugia> dl_canho_lichsugia { get; set; }
        public virtual DbSet<dl_canho_temp> dl_canho_temp { get; set; }
        public virtual DbSet<dl_chudautu> dl_chudautu { get; set; }
        public virtual DbSet<dl_configs> dl_configs { get; set; }
        public virtual DbSet<dl_dangtin> dl_dangtin { get; set; }
        public virtual DbSet<dl_dm_chunha> dl_dm_chunha { get; set; }
        public virtual DbSet<dl_dm_chunha_chitiet> dl_dm_chunha_chitiet { get; set; }
        public virtual DbSet<dl_dm_loai_nhu_cau> dl_dm_loai_nhu_cau { get; set; }
        public virtual DbSet<dl_dm_phuong_xa> dl_dm_phuong_xa { get; set; }
        public virtual DbSet<dl_dm_quan_huyen> dl_dm_quan_huyen { get; set; }
        public virtual DbSet<dl_dm_tinh_thanh_pho> dl_dm_tinh_thanh_pho { get; set; }
        public virtual DbSet<dl_dm_tinhtrang_duan> dl_dm_tinhtrang_duan { get; set; }
        public virtual DbSet<dl_dm_tinhtrangcanho> dl_dm_tinhtrangcanho { get; set; }
        public virtual DbSet<dl_dm_trangthai_yeucau> dl_dm_trangthai_yeucau { get; set; }
        public virtual DbSet<dl_duan> dl_duan { get; set; }
        public virtual DbSet<dl_historys> dl_historys { get; set; }
        public virtual DbSet<dl_loaiduan> dl_loaiduan { get; set; }
        public virtual DbSet<dl_loaithongbao> dl_loaithongbao { get; set; }
        public virtual DbSet<dl_nguoidung_phanquyen_nhomnguoidung> dl_nguoidung_phanquyen_nhomnguoidung { get; set; }
        public virtual DbSet<dl_nguoidung_tinhtrang> dl_nguoidung_tinhtrang { get; set; }
        public virtual DbSet<dl_nhom_nguoi_dung> dl_nhom_nguoi_dung { get; set; }
        public virtual DbSet<dl_nhom_nguoi_dung_level> dl_nhom_nguoi_dung_level { get; set; }
        public virtual DbSet<dl_nhomquyen> dl_nhomquyen { get; set; }
        public virtual DbSet<dl_phan_quyen> dl_phan_quyen { get; set; }
        public virtual DbSet<dl_quyen> dl_quyen { get; set; }
        public virtual DbSet<dl_thongbao> dl_thongbao { get; set; }
        public virtual DbSet<dl_thongbao_nguoidung> dl_thongbao_nguoidung { get; set; }
        public virtual DbSet<dl_thongbao_phanquyen> dl_thongbao_phanquyen { get; set; }
        public virtual DbSet<dl_yeucau> dl_yeucau { get; set; }
        public virtual DbSet<dl_yeucau_canho> dl_yeucau_canho { get; set; }
        public virtual DbSet<dl_yeucau_nhucau> dl_yeucau_nhucau { get; set; }
        public virtual DbSet<dl_yeucau_trangthai> dl_yeucau_trangthai { get; set; }
        public virtual DbSet<wp_actionscheduler_actions> wp_actionscheduler_actions { get; set; }
        public virtual DbSet<wp_actionscheduler_claims> wp_actionscheduler_claims { get; set; }
        public virtual DbSet<wp_actionscheduler_groups> wp_actionscheduler_groups { get; set; }
        public virtual DbSet<wp_actionscheduler_logs> wp_actionscheduler_logs { get; set; }
        public virtual DbSet<wp_blc_filters> wp_blc_filters { get; set; }
        public virtual DbSet<wp_blc_instances> wp_blc_instances { get; set; }
        public virtual DbSet<wp_blc_links> wp_blc_links { get; set; }
        public virtual DbSet<wp_blc_synch> wp_blc_synch { get; set; }
        public virtual DbSet<wp_commentmeta> wp_commentmeta { get; set; }
        public virtual DbSet<wp_comments> wp_comments { get; set; }
        public virtual DbSet<wp_links> wp_links { get; set; }
        public virtual DbSet<wp_myhome_attributes> wp_myhome_attributes { get; set; }
        public virtual DbSet<wp_myhome_locations> wp_myhome_locations { get; set; }
        public virtual DbSet<wp_options> wp_options { get; set; }
        public virtual DbSet<wp_postmeta> wp_postmeta { get; set; }
        public virtual DbSet<wp_posts> wp_posts { get; set; }
        public virtual DbSet<wp_rank_math_404_logs> wp_rank_math_404_logs { get; set; }
        public virtual DbSet<wp_rank_math_analytics_adsense> wp_rank_math_analytics_adsense { get; set; }
        public virtual DbSet<wp_rank_math_analytics_ga> wp_rank_math_analytics_ga { get; set; }
        public virtual DbSet<wp_rank_math_analytics_gsc> wp_rank_math_analytics_gsc { get; set; }
        public virtual DbSet<wp_rank_math_analytics_keyword_manager> wp_rank_math_analytics_keyword_manager { get; set; }
        public virtual DbSet<wp_rank_math_analytics_object_links> wp_rank_math_analytics_object_links { get; set; }
        public virtual DbSet<wp_rank_math_analytics_objects> wp_rank_math_analytics_objects { get; set; }
        public virtual DbSet<wp_rank_math_internal_links> wp_rank_math_internal_links { get; set; }
        public virtual DbSet<wp_rank_math_internal_meta> wp_rank_math_internal_meta { get; set; }
        public virtual DbSet<wp_rank_math_redirections> wp_rank_math_redirections { get; set; }
        public virtual DbSet<wp_rank_math_redirections_cache> wp_rank_math_redirections_cache { get; set; }
        public virtual DbSet<wp_rank_math_sc_analytics> wp_rank_math_sc_analytics { get; set; }
        public virtual DbSet<wp_term_relationships> wp_term_relationships { get; set; }
        public virtual DbSet<wp_term_taxonomy> wp_term_taxonomy { get; set; }
        public virtual DbSet<wp_termmeta> wp_termmeta { get; set; }
        public virtual DbSet<wp_terms> wp_terms { get; set; }
        public virtual DbSet<wp_usermeta> wp_usermeta { get; set; }
        public virtual DbSet<wp_users> wp_users { get; set; }
        public virtual DbSet<wp_wc_admin_note_actions> wp_wc_admin_note_actions { get; set; }
        public virtual DbSet<wp_wc_admin_notes> wp_wc_admin_notes { get; set; }
        public virtual DbSet<wp_wc_category_lookup> wp_wc_category_lookup { get; set; }
        public virtual DbSet<wp_wc_customer_lookup> wp_wc_customer_lookup { get; set; }
        public virtual DbSet<wp_wc_download_log> wp_wc_download_log { get; set; }
        public virtual DbSet<wp_wc_order_coupon_lookup> wp_wc_order_coupon_lookup { get; set; }
        public virtual DbSet<wp_wc_order_product_lookup> wp_wc_order_product_lookup { get; set; }
        public virtual DbSet<wp_wc_order_stats> wp_wc_order_stats { get; set; }
        public virtual DbSet<wp_wc_order_tax_lookup> wp_wc_order_tax_lookup { get; set; }
        public virtual DbSet<wp_wc_product_meta_lookup> wp_wc_product_meta_lookup { get; set; }
        public virtual DbSet<wp_wc_reserved_stock> wp_wc_reserved_stock { get; set; }
        public virtual DbSet<wp_wc_tax_rate_classes> wp_wc_tax_rate_classes { get; set; }
        public virtual DbSet<wp_wc_webhooks> wp_wc_webhooks { get; set; }
        public virtual DbSet<wp_woocommerce_api_keys> wp_woocommerce_api_keys { get; set; }
        public virtual DbSet<wp_woocommerce_attribute_taxonomies> wp_woocommerce_attribute_taxonomies { get; set; }
        public virtual DbSet<wp_woocommerce_downloadable_product_permissions> wp_woocommerce_downloadable_product_permissions { get; set; }
        public virtual DbSet<wp_woocommerce_log> wp_woocommerce_log { get; set; }
        public virtual DbSet<wp_woocommerce_order_itemmeta> wp_woocommerce_order_itemmeta { get; set; }
        public virtual DbSet<wp_woocommerce_order_items> wp_woocommerce_order_items { get; set; }
        public virtual DbSet<wp_woocommerce_payment_tokenmeta> wp_woocommerce_payment_tokenmeta { get; set; }
        public virtual DbSet<wp_woocommerce_payment_tokens> wp_woocommerce_payment_tokens { get; set; }
        public virtual DbSet<wp_woocommerce_sessions> wp_woocommerce_sessions { get; set; }
        public virtual DbSet<wp_woocommerce_shipping_zone_locations> wp_woocommerce_shipping_zone_locations { get; set; }
        public virtual DbSet<wp_woocommerce_shipping_zone_methods> wp_woocommerce_shipping_zone_methods { get; set; }
        public virtual DbSet<wp_woocommerce_shipping_zones> wp_woocommerce_shipping_zones { get; set; }
        public virtual DbSet<wp_woocommerce_tax_rate_locations> wp_woocommerce_tax_rate_locations { get; set; }
        public virtual DbSet<wp_woocommerce_tax_rates> wp_woocommerce_tax_rates { get; set; }
        public virtual DbSet<dl_canho_tempitem> dl_canho_tempitem { get; set; }
        public virtual DbSet<wp_revslider_css> wp_revslider_css { get; set; }
        public virtual DbSet<wp_revslider_layer_animations> wp_revslider_layer_animations { get; set; }
        public virtual DbSet<wp_revslider_navigations> wp_revslider_navigations { get; set; }
        public virtual DbSet<wp_revslider_sliders> wp_revslider_sliders { get; set; }
        public virtual DbSet<wp_revslider_slides> wp_revslider_slides { get; set; }
        public virtual DbSet<wp_revslider_static_slides> wp_revslider_static_slides { get; set; }
        public virtual DbSet<v_canho_giohang> v_canho_giohang { get; set; }
        public virtual DbSet<v_dm_huong> v_dm_huong { get; set; }
        public virtual DbSet<v_duan> v_duan { get; set; }
        public virtual DbSet<v_history> v_history { get; set; }
        public virtual DbSet<v_nhanvien> v_nhanvien { get; set; }
        public virtual DbSet<v_phanquyen> v_phanquyen { get; set; }
        public virtual DbSet<v_phong_ngu> v_phong_ngu { get; set; }
        public virtual DbSet<v_thongtin_chunha> v_thongtin_chunha { get; set; }
        public virtual DbSet<v_tindang> v_tindang { get; set; }
        public virtual DbSet<v_users> v_users { get; set; }
        public virtual DbSet<v_wc> v_wc { get; set; }
        public virtual DbSet<dl_dm_loai> dl_dm_loai { get; set; }
        public virtual DbSet<v_canho> v_canho { get; set; }
        public virtual DbSet<dl_canho_giohangsalesman> dl_canho_giohangsalesman { get; set; }
    
        public virtual ObjectResult<Pro_CanHoChiTiet_Result> Pro_CanHoChiTiet(Nullable<long> parIDCanHo)
        {
            var parIDCanHoParameter = parIDCanHo.HasValue ?
                new ObjectParameter("parIDCanHo", parIDCanHo) :
                new ObjectParameter("parIDCanHo", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Pro_CanHoChiTiet_Result>("Pro_CanHoChiTiet", parIDCanHoParameter);
        }
    
        public virtual ObjectResult<proc_canho_giohang_Result> proc_canho_giohang(Nullable<double> pardientich, Nullable<double> pargiaban, Nullable<double> pargiathue, Nullable<double> pargiabanusd, Nullable<int> pargiathueusd)
        {
            var pardientichParameter = pardientich.HasValue ?
                new ObjectParameter("pardientich", pardientich) :
                new ObjectParameter("pardientich", typeof(double));
    
            var pargiabanParameter = pargiaban.HasValue ?
                new ObjectParameter("pargiaban", pargiaban) :
                new ObjectParameter("pargiaban", typeof(double));
    
            var pargiathueParameter = pargiathue.HasValue ?
                new ObjectParameter("pargiathue", pargiathue) :
                new ObjectParameter("pargiathue", typeof(double));
    
            var pargiabanusdParameter = pargiabanusd.HasValue ?
                new ObjectParameter("pargiabanusd", pargiabanusd) :
                new ObjectParameter("pargiabanusd", typeof(double));
    
            var pargiathueusdParameter = pargiathueusd.HasValue ?
                new ObjectParameter("pargiathueusd", pargiathueusd) :
                new ObjectParameter("pargiathueusd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_canho_giohang_Result>("proc_canho_giohang", pardientichParameter, pargiabanParameter, pargiathueParameter, pargiabanusdParameter, pargiathueusdParameter);
        }
    }
}
