//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_canho_giohang
    {
        public decimal IDCanHo { get; set; }
        public string DuAn { get; set; }
        public string Thap { get; set; }
        public string Tang { get; set; }
        public string SoCan { get; set; }
        public string TenChuNha { get; set; }
        public string LienHe { get; set; }
        public string Salesman { get; set; }
        public string ThongTinChuNha { get; set; }
        public string TinhTrang { get; set; }
        public string LoaiCanHo { get; set; }
        public string LoaiBanGiao { get; set; }
        public string PhongNgu { get; set; }
        public string WC { get; set; }
        public Nullable<double> DienTich { get; set; }
        public string VIEW { get; set; }
        public string HuongCua { get; set; }
        public string HuongBanCong { get; set; }
        public string MatKhauCua { get; set; }
        public string GiaHopDong { get; set; }
        public string GiaChuNhaGui { get; set; }
        public string GiaChotBan { get; set; }
        public string GiaChaoBan { get; set; }
        public string GiaThueNet { get; set; }
        public string GiaThueBaoPhi { get; set; }
        public string GhiChuAdmin { get; set; }
        public string GhiChuQuanLy { get; set; }
        public string GhiChuSales { get; set; }
        public string GhiChuCanHo { get; set; }
        public string QuocTich { get; set; }
        public string NgayTao { get; set; }
        public string NgaySua { get; set; }
        public Nullable<bool> Del { get; set; }
        public Nullable<double> GiaBan { get; set; }
        public string GiaBanDVT { get; set; }
        public Nullable<double> GiaBanUSD { get; set; }
        public Nullable<double> GiaGoc { get; set; }
        public string GiaGocDVT { get; set; }
        public Nullable<double> GiaGocUSD { get; set; }
    }
}
