//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_duan
    {
        public long duan { get; set; }
        public string ma_duan { get; set; }
        public string ten_duan { get; set; }
        public Nullable<int> loai_duan { get; set; }
        public Nullable<int> chudautu { get; set; }
        public Nullable<int> tinhtrang { get; set; }
        public string tinh_thanhpho { get; set; }
        public string quanhuyen { get; set; }
        public string phuongxa { get; set; }
        public string duong { get; set; }
        public string sonha { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string website { get; set; }
        public string mota { get; set; }
        public string ghichu { get; set; }
        public string DiaChi { get; set; }
    }
}
