//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_history
    {
        public long Id { get; set; }
        public string Key { get; set; }
        public string Content { get; set; }
        public string Type { get; set; }
        public string Link { get; set; }
        public string display_name { get; set; }
        public string Ngay { get; set; }
    }
}
