//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_nhanvien
    {
        public decimal id { get; set; }
        public string user_login { get; set; }
        public string user_email { get; set; }
        public string dienthoai { get; set; }
        public string ten_nguoidung_tinhtrang { get; set; }
        public string ma_nhom_nguoi_dung { get; set; }
    }
}
