//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_phanquyen
    {
        public int id { get; set; }
        public string tenquyen { get; set; }
        public int stt { get; set; }
        public string ten_nhom { get; set; }
        public string @checked { get; set; }
        public string quyen { get; set; }
        public string GhiChu { get; set; }
    }
}
