//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_thongtin_chunha
    {
        public long IdChuNha { get; set; }
        public string TenChuNha { get; set; }
        public string LienHe { get; set; }
        public string QuocTich { get; set; }
        public string GhiChu { get; set; }
    }
}
