//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tindang
    {
        public decimal id { get; set; }
        public string post_title { get; set; }
        public string post_status { get; set; }
        public string hinh_dai_dien { get; set; }
        public string post_date { get; set; }
        public Nullable<decimal> du_an { get; set; }
        public Nullable<decimal> chu_dau_tu { get; set; }
        public Nullable<decimal> trang_thai { get; set; }
        public Nullable<decimal> loai { get; set; }
        public string loai_kinh_doanh { get; set; }
        public Nullable<decimal> huong { get; set; }
        public Nullable<decimal> views { get; set; }
        public string dia_chi { get; set; }
        public string dien_tich { get; set; }
        public string phong_ngu { get; set; }
        public string wc { get; set; }
        public string gia_ban { get; set; }
        public string gia_ban_ty { get; set; }
        public string gia_ban_trieu { get; set; }
        public string gia_ban_usd { get; set; }
        public string gia_thue_ty { get; set; }
        public string gia_thue_trieu { get; set; }
        public string gia_thue_usd { get; set; }
        public string gia_thue { get; set; }
        public string author { get; set; }
        public System.DateTime post_modified { get; set; }
        public Nullable<long> vi_tri { get; set; }
        public Nullable<decimal> NguoiDung { get; set; }
    }
}
