//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_actionscheduler_actions
    {
        public decimal action_id { get; set; }
        public string hook { get; set; }
        public string status { get; set; }
        public System.DateTime scheduled_date_gmt { get; set; }
        public System.DateTime scheduled_date_local { get; set; }
        public string args { get; set; }
        public string schedule { get; set; }
        public decimal group_id { get; set; }
        public int attempts { get; set; }
        public System.DateTime last_attempt_gmt { get; set; }
        public System.DateTime last_attempt_local { get; set; }
        public decimal claim_id { get; set; }
        public string extended_args { get; set; }
    }
}
