//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_actionscheduler_logs
    {
        public decimal log_id { get; set; }
        public decimal action_id { get; set; }
        public string message { get; set; }
        public System.DateTime log_date_gmt { get; set; }
        public System.DateTime log_date_local { get; set; }
    }
}
