//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_blc_instances
    {
        public long instance_id { get; set; }
        public long link_id { get; set; }
        public long container_id { get; set; }
        public string container_type { get; set; }
        public string link_text { get; set; }
        public string parser_type { get; set; }
        public string container_field { get; set; }
        public string link_context { get; set; }
        public string raw_url { get; set; }
    }
}
