//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_blc_links
    {
        public long link_id { get; set; }
        public string url { get; set; }
        public System.DateTime first_failure { get; set; }
        public System.DateTime last_check { get; set; }
        public System.DateTime last_success { get; set; }
        public System.DateTime last_check_attempt { get; set; }
        public long check_count { get; set; }
        public string final_url { get; set; }
        public int redirect_count { get; set; }
        public string log { get; set; }
        public short http_code { get; set; }
        public string status_code { get; set; }
        public string status_text { get; set; }
        public float request_duration { get; set; }
        public bool timeout { get; set; }
        public bool broken { get; set; }
        public bool warning { get; set; }
        public bool may_recheck { get; set; }
        public bool being_checked { get; set; }
        public string result_hash { get; set; }
        public bool false_positive { get; set; }
        public bool dismissed { get; set; }
    }
}
