//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_blc_synch
    {
        public long container_id { get; set; }
        public string container_type { get; set; }
        public byte synched { get; set; }
        public System.DateTime last_synch { get; set; }
    }
}
