//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_myhome_attributes
    {
        public decimal ID { get; set; }
        public string attribute_name { get; set; }
        public string attribute_slug { get; set; }
        public string attribute_type { get; set; }
        public long form_order { get; set; }
        public long @base { get; set; }
        public string base_slug { get; set; }
    }
}
