//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_rank_math_analytics_objects
    {
        public decimal id { get; set; }
        public System.DateTime created { get; set; }
        public string title { get; set; }
        public string page { get; set; }
        public string object_type { get; set; }
        public string object_subtype { get; set; }
        public decimal object_id { get; set; }
        public string primary_key { get; set; }
        public sbyte seo_score { get; set; }
        public sbyte page_score { get; set; }
        public bool is_indexable { get; set; }
        public string schemas_in_use { get; set; }
        public Nullable<double> desktop_interactive { get; set; }
        public Nullable<double> desktop_pagescore { get; set; }
        public Nullable<double> mobile_interactive { get; set; }
        public Nullable<double> mobile_pagescore { get; set; }
        public System.DateTime pagespeed_refreshed { get; set; }
    }
}
