//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_rank_math_internal_links
    {
        public decimal id { get; set; }
        public string url { get; set; }
        public decimal post_id { get; set; }
        public decimal target_post_id { get; set; }
        public string type { get; set; }
    }
}
