//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_rank_math_internal_meta
    {
        public decimal object_id { get; set; }
        public Nullable<long> internal_link_count { get; set; }
        public Nullable<long> external_link_count { get; set; }
        public Nullable<long> incoming_link_count { get; set; }
    }
}
