//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_rank_math_analytics_object_links
    {
        public decimal id { get; set; }
        public decimal object_id { get; set; }
        public string link { get; set; }
        public string type { get; set; }
        public string rel { get; set; }
        public sbyte status { get; set; }
    }
}
