//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_rank_math_analytics_keyword_manager
    {
        public decimal id { get; set; }
        public string keyword { get; set; }
        public string collection { get; set; }
        public bool is_active { get; set; }
    }
}
