//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_rank_math_analytics_gsc
    {
        public decimal id { get; set; }
        public System.DateTime created { get; set; }
        public string query { get; set; }
        public string page { get; set; }
        public int clicks { get; set; }
        public int impressions { get; set; }
        public double position { get; set; }
        public double ctr { get; set; }
    }
}
