//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_rank_math_404_logs
    {
        public decimal id { get; set; }
        public string uri { get; set; }
        public System.DateTime accessed { get; set; }
        public decimal times_accessed { get; set; }
        public string ip { get; set; }
        public string referer { get; set; }
        public string user_agent { get; set; }
    }
}
