//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_rank_math_redirections
    {
        public decimal id { get; set; }
        public string sources { get; set; }
        public string url_to { get; set; }
        public int header_code { get; set; }
        public decimal hits { get; set; }
        public string status { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public System.DateTime last_accessed { get; set; }
    }
}
