//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_revslider_navigations
    {
        public int id { get; set; }
        public string name { get; set; }
        public string handle { get; set; }
        public string css { get; set; }
        public string markup { get; set; }
        public string settings { get; set; }
    }
}
