//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_wc_customer_lookup
    {
        public decimal customer_id { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public string username { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_last_active { get; set; }
        public Nullable<System.DateTime> date_registered { get; set; }
        public string country { get; set; }
        public string postcode { get; set; }
        public string city { get; set; }
        public string state { get; set; }
    }
}
