//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_attribute_taxonomies
    {
        public decimal attribute_id { get; set; }
        public string attribute_name { get; set; }
        public string attribute_label { get; set; }
        public string attribute_type { get; set; }
        public string attribute_orderby { get; set; }
        public int attribute_public { get; set; }
    }
}
