//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_tax_rates
    {
        public decimal tax_rate_id { get; set; }
        public string tax_rate_country { get; set; }
        public string tax_rate_state { get; set; }
        public string tax_rate { get; set; }
        public string tax_rate_name { get; set; }
        public decimal tax_rate_priority { get; set; }
        public int tax_rate_compound { get; set; }
        public int tax_rate_shipping { get; set; }
        public decimal tax_rate_order { get; set; }
        public string tax_rate_class { get; set; }
    }
}
