//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_api_keys
    {
        public decimal key_id { get; set; }
        public decimal user_id { get; set; }
        public string description { get; set; }
        public string permissions { get; set; }
        public string consumer_key { get; set; }
        public string consumer_secret { get; set; }
        public string nonces { get; set; }
        public string truncated_key { get; set; }
        public Nullable<System.DateTime> last_access { get; set; }
    }
}
