//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_order_items
    {
        public decimal order_item_id { get; set; }
        public string order_item_name { get; set; }
        public string order_item_type { get; set; }
        public decimal order_id { get; set; }
    }
}
