//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_wc_reserved_stock
    {
        public long order_id { get; set; }
        public long product_id { get; set; }
        public double stock_quantity { get; set; }
        public System.DateTime timestamp { get; set; }
        public System.DateTime expires { get; set; }
    }
}
