//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_wc_order_product_lookup
    {
        public decimal order_item_id { get; set; }
        public decimal order_id { get; set; }
        public decimal product_id { get; set; }
        public decimal variation_id { get; set; }
        public Nullable<decimal> customer_id { get; set; }
        public System.DateTime date_created { get; set; }
        public int product_qty { get; set; }
        public double product_net_revenue { get; set; }
        public double product_gross_revenue { get; set; }
        public double coupon_amount { get; set; }
        public double tax_amount { get; set; }
        public double shipping_amount { get; set; }
        public double shipping_tax_amount { get; set; }
    }
}
