//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_wc_order_coupon_lookup
    {
        public decimal order_id { get; set; }
        public long coupon_id { get; set; }
        public System.DateTime date_created { get; set; }
        public double discount_amount { get; set; }
    }
}
