//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_shipping_zone_methods
    {
        public decimal zone_id { get; set; }
        public decimal instance_id { get; set; }
        public string method_id { get; set; }
        public decimal method_order { get; set; }
        public bool is_enabled { get; set; }
    }
}
