//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_log
    {
        public decimal log_id { get; set; }
        public System.DateTime timestamp { get; set; }
        public short level { get; set; }
        public string source { get; set; }
        public string message { get; set; }
        public string context { get; set; }
    }
}
