//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_tax_rate_locations
    {
        public decimal location_id { get; set; }
        public string location_code { get; set; }
        public decimal tax_rate_id { get; set; }
        public string location_type { get; set; }
    }
}
