//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_wc_admin_notes
    {
        public decimal note_id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string locale { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string content_data { get; set; }
        public string status { get; set; }
        public string source { get; set; }
        public System.DateTime date_created { get; set; }
        public Nullable<System.DateTime> date_reminder { get; set; }
        public bool is_snoozable { get; set; }
        public string layout { get; set; }
        public string image { get; set; }
        public bool is_deleted { get; set; }
        public string icon { get; set; }
    }
}
