//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_woocommerce_payment_tokens
    {
        public decimal token_id { get; set; }
        public string gateway_id { get; set; }
        public string token { get; set; }
        public decimal user_id { get; set; }
        public string type { get; set; }
        public bool is_default { get; set; }
    }
}
