//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_wc_admin_note_actions
    {
        public decimal action_id { get; set; }
        public decimal note_id { get; set; }
        public string name { get; set; }
        public string label { get; set; }
        public string query { get; set; }
        public string status { get; set; }
        public bool is_primary { get; set; }
        public string actioned_text { get; set; }
    }
}
